{% set name = "aiida-pseudo" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e3fa67bc8deb2d7220b5c26b880c8630f61f3b54816ff737fb91a68b15429df9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.4,<4
    - pip
    - python >=3.9
  run:
    - aiida-core ~=2.6
    - click ~=8.0
    - pint ~=0.23.0
    - python >=3.9
    - requests ~=2.20

test:
  imports:
    - aiida_pseudo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/aiida-pseudo/
  summary: AiiDA plugin that simplifies working with pseudo potentials.
  dev_url: https://github.com/aiidateam/aiida-pseudo
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjsewell
    - mbercx
    - sphuber
