{% set name = "aiida-pseudo" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 440fc8939a474a91c076a84ba074d6d47e44351d180e3affef41af4b5a768a13

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.4,<4
    - pip
    - python >=3.8
  run:
    - aiida-core ~=2.1
    - click ~=8.0
    - pint ~=0.16.1
    - python >=3.8
    - requests ~=2.20

test:
  imports:
    - aiida_pseudo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/aiida-pseudo/
  summary: AiiDA plugin that simplifies working with pseudo potentials.
  dev_url: https://github.com/aiidateam/aiida-pseudo
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjsewell
    - mbercx
    - sphuber
