{% set name = "aiida-pseudo" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9e6cc5bf59a368633bed2c7d19e84f89a29fc1d72a8031b9774062c7c018f9bb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.4,<4
    - pip
    - python >=3.9
  run:
    - aiida-core ~=2.6
    - click ~=8.0,<8.2
    - pint >=0.23.0,<0.25.0
    - python >=3.9
    - requests ~=2.20

test:
  imports:
    - aiida_pseudo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/aiida-pseudo/
  summary: AiiDA plugin that simplifies working with pseudo potentials.
  dev_url: https://github.com/aiidateam/aiida-pseudo
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjsewell
    - mbercx
    - sphuber
