{% set name = "aiida-pseudo" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiida-pseudo-{{ version }}.tar.gz
  sha256: cfd94e62659d7d26b35635023ea3727934aeeb66df1fb67388936a23a4aebf41

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.4,<4
    - pip
    - python >=3.8
  run:
    - aiida-core ~=2.0
    - click ~=8.0
    - pint ~=0.16.1
    - python >=3.8
    - requests ~=2.20

test:
  imports:
    - aiida_pseudo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/aiida-pseudo/
  summary: AiiDA plugin that simplifies working with pseudo potentials.
  dev_url: https://github.com/aiidateam/aiida-pseudo
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjsewell
